# Generated by Django 5.2 on 2025-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
