# Generated by Django 5.2 on 2025-06-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_supabase_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supabase_image_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
