# Generated by Django 5.2 on 2025-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='mcq_options_count',
            field=models.IntegerField(default=2),
        ),
    ]
