# Generated by Django 5.2 on 2025-06-14 17:51

import create_exam_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0002_alter_exam_output_pdf_alter_exam_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='output_pdf',
            field=models.FileField(blank=True, null=True, upload_to='exam_outputs'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pdf_file',
            field=models.FileField(upload_to=create_exam_app.models.pdf_upload_path),
        ),
    ]
