# Generated by Django 5.2 on 2025-04-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0002_alter_exam_mcq_options_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='answers_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='options_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='has_options',
            field=models.BooleanField(default=False),
        ),
    ]
