# Generated by Django 5.2 on 2025-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0003_exam_answers_generated_exam_options_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='output_pdf',
            field=models.FileField(blank=True, null=True, upload_to='exam_outputs'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
