# Generated by Django 5.2 on 2025-06-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0003_alter_exam_output_pdf_alter_exam_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='output_pdf',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pdf_file',
            field=models.URLField(max_length=500),
        ),
    ]
