# Generated by Django 5.2 on 2025-04-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0004_exam_output_pdf_exam_question_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
