# Generated by Django 5.2 on 2025-06-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0005_alter_exam_output_pdf_alter_exam_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='output_pdf',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='exam',
            name='language',
            field=models.CharField(default='english', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='output_pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='output_pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='output_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='pdf_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='pdf_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='pdf_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
