# Generated by Django 5.2 on 2025-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0005_alter_exam_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='minus_marking_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
