# Generated by Django 5.2 on 2025-04-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0006_alter_exam_minus_marking_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('Generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
