# Generated by Django 5.2 on 2025-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0006_remove_exam_output_pdf_remove_exam_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
