# Generated by Django 5.2 on 2025-04-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0007_alter_exam_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='each_question_marks',
            field=models.IntegerField(default=1),
        ),
    ]
