# Generated by Django 5.2 on 2025-06-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0007_alter_exam_processing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='language',
        ),
    ]
