# Generated by Django 5.2 on 2025-04-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0008_exam_each_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='corrected_ans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='wrong_ans',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
