# Generated by Django 5.2 on 2025-04-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0009_examsession_corrected_ans_examsession_wrong_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='unanswered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
