# Generated by Django 5.2 on 2025-04-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0010_examsession_unanswered'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='status',
            field=models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong'), ('unanswered', 'Unanswered')], default='unanswered', max_length=10),
        ),
    ]
