# Generated by Django 5.2 on 2025-04-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam_app', '0011_useranswer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='time_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
